# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaa269c0646920c1d9169a5d42bd1b0ce97ceeeae9d2562cdf9dcb1c3eca3b9c0f1f31346186b748eafa85bca425a1acbd8b6f0c38781b46c8e442b7e486782e

test:
  secret_key_base: 516b4aa4c5aae1b73fd88def8c42bb8c5333ff8a1fd545a43fcfef1b791fde074aa7a055f457c450b324b90e9cffed35d9a3f6234b688b12822d48319e44a40a

production:
  secret_key_base: 780bf1e7972044d53a5ed1f75da9dd55b8eabb946c189a618f2592b523a5821a39e6d7d3adb342a0eb9ea6aecf11a8d7c2ee47725681ee9b275a2eada4c965be
